services:
  mqtt-proxy:
    image: confluentinc/cp-kafka-mqtt:latest
    container_name: mqtt-proxy
    ports:
      - "1883:1883"
      - "8883:8883"
    environment:
      KAFKA_MQTT_BOOTSTRAP_SERVERS: '192.168.137.1:9092'
      KAFKA_MQTT_TOPIC_REGEX_LIST: "test-temp:test-temp, test:test" # correspondance entre les topics MQTT et Kafka (kafka:mqtt)
    networks:
      - default